language: php

php:
  - 5.3
  - 5.4

before_script:
  - composer update --dev
  - pyrus channel-discover pear.phpunit.de
  - pyrus channel-discover pear.phpmd.org
  - pyrus channel-discover pear.pdepend.org
  - pyrus install --force phpunit/DbUnit
  - pyrus install pear/PHP_CodeSniffer
  - pyrus install --alldeps phpmd/PHP_PMD
  - phpenv rehash

script:
  - ant
