language: php

php:
  - 5.4
  - 5.5

before_script:
  - composer self-update --dev
  - composer install
  - pear channel-discover pear.phpunit.de
  - pear channel-discover pear.phpmd.org
  - pear channel-discover pear.pdepend.org
  - pear install --force phpunit/DbUnit
  - pear install --force pear/PHP_CodeSniffer
  - pear install --force phpmd/PHP_PMD
  - phpenv rehash

script:
  - ant travis-build
  - phpunit --configuration phpunit.travis.xml
  - cli/tracker.php test run
