language: php

php:
  - 5.4
  - 5.5

env: JTRACKER_ENVIRONMENT=travis

before_install:
  - sh -e .travis/scripts/apt-get.sh
  - sh -e .travis/scripts/apache2-vhost.sh
  - sh -e .travis/scripts/apache2-configure.sh

before_script:
  - composer self-update
  - composer install

script:
  - bin/jtracker test run
  - vendor/bin/behat -v --config behat-travis.yml
